#!/usr/bin/env python3
"""Build a clean, conflict-free restore.sql from a Supabase `db_cluster` backup
so it can be loaded into a BRAND-NEW Supabase project.

Why this exists: Supabase's downloadable backup is a full `pg_dumpall` cluster
dump. You cannot pipe it straight into a new project — it recreates Supabase's
own roles and managed schemas (auth/storage/realtime/vault), which already exist
and are owned by privileged roles. This script extracts ONLY the things we own:

  * the entire `public` schema (tables, data, functions, indexes, constraints,
    RLS policies, triggers, and the real GRANTs the app needs)
  * the `auth.users` + `auth.identities` rows, so existing logins keep working
    and the same user UUIDs stay linked to all user data (study progress, etc.)
  * any custom trigger on an `auth` table that calls a `public.*` function
    (e.g. on_auth_user_created -> public.handle_new_user) — emitted AFTER COMMIT
    so a privilege error there can't roll back the data restore

It drops things the non-superuser `postgres` role can't or shouldn't run against
a managed project: CREATE ROLE, managed-schema DDL, and `ALTER DEFAULT
PRIVILEGES FOR ROLE <other>` (the latter is what fails with "permission denied
to change default privileges").

Usage:
    gunzip -c ~/Downloads/db_cluster-XX.backup.gz > db_cluster.sql
    python3 scripts/restore-from-cluster-dump.py db_cluster.sql restore.sql
    psql "postgresql://postgres:[PW]@db.[NEW-REF].supabase.co:5432/postgres" \
         -v ON_ERROR_STOP=1 -f restore.sql

See CLAUDE.md ("Backups & Disaster Recovery") for the full procedure.
"""
import re
import sys

if len(sys.argv) != 3:
    sys.exit(f"usage: {sys.argv[0]} <decompressed-cluster-dump.sql> <output-restore.sql>")

SRC, OUT = sys.argv[1], sys.argv[2]

with open(SRC) as f:
    lines = f.read().split("\n")

# pg_dump prefixes every object with a 3-line header:
#   --
#   -- Name: <name>; Type: <type>; Schema: <schema>; Owner: <owner>
#   --       (data sections use "-- Data for Name: ...")
header_re = re.compile(
    r"^-- (?:Data for )?Name: (?P<name>.*?); Type: (?P<type>[^;]+); Schema: (?P<schema>[^;]+); Owner:"
)

starts = []
for i in range(len(lines) - 2):
    if lines[i] == "--" and lines[i + 2] == "--":
        m = header_re.match(lines[i + 1])
        if m:
            starts.append((i, m.group("schema"), m.group("type").strip(), m.group("name")))

sections = []
for idx, (start, schema, typ, name) in enumerate(starts):
    end = starts[idx + 1][0] if idx + 1 < len(starts) else len(lines)
    sections.append(
        {"schema": schema, "type": typ, "name": name, "body": "\n".join(lines[start:end]).rstrip("\n")}
    )


def is_public(sec):
    # Everything we own is in `public`, EXCEPT ALTER DEFAULT PRIVILEGES blocks:
    # they only affect FUTURE objects, and the "FOR ROLE supabase_admin" variants
    # fail because non-superuser `postgres` can't change another role's defaults.
    return sec["schema"] == "public" and sec["type"] != "DEFAULT ACL"


def is_auth_login_data(sec):
    # Keep just enough auth state to preserve the same users + their UUIDs.
    # (sessions/refresh_tokens are tied to the old JWT secret — let users re-login.)
    return sec["type"] == "TABLE DATA" and sec["schema"] == "auth" and sec["name"] in ("users", "identities")


def is_custom_auth_trigger(sec):
    # A trigger on an auth.* table that calls one of our public functions.
    return sec["type"].startswith("TRIGGER") and sec["schema"] == "auth" and "public." in sec["body"]


public_sections = [s for s in sections if is_public(s)]
auth_data = [s for s in sections if is_auth_login_data(s)]
auth_triggers = [s for s in sections if is_custom_auth_trigger(s)]

PREAMBLE = """\
--
-- Restore: public schema + existing users into a NEW Supabase project.
-- Generated by scripts/restore-from-cluster-dump.py
-- Run with:  psql "<DIRECT_CONNECTION_STRING>" -v ON_ERROR_STOP=1 -f restore.sql
--
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;  -- functions may reference tables created later
SET client_min_messages = warning;
SET row_security = off;

BEGIN;

-- Extensions the public schema depends on (no-op if Supabase already enabled them).
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "pgcrypto"  WITH SCHEMA extensions;
"""

with open(OUT, "w") as f:
    f.write(PREAMBLE)

    # auth users/identities first, so they exist before public FK constraints are
    # validated in the post-data section and before public user-data is loaded.
    if auth_data:
        f.write("\n-- Preserve existing users (same UUIDs keep all user data linked; "
                "old passwords keep working).\n")
        for s in auth_data:
            f.write("\n" + s["body"] + "\n")

    f.write("\n-- ===== public schema objects + data =====\n")
    for s in public_sections:
        f.write("\n\n" + s["body"] + "\n")

    f.write("\n\nCOMMIT;\n")

    # Custom auth triggers AFTER commit: creating a trigger on the managed
    # auth.users table can need elevated privileges; don't let it roll back data.
    for s in auth_triggers:
        f.write("\n-- Custom trigger on an auth table (run separately; non-critical).\n")
        f.write("-- If it errors on privileges, paste it into the Supabase SQL editor.\n")
        f.write(s["body"] + "\n")

# ---- summary ----
print(f"public objects kept : {len(public_sections)}")
print(f"auth data sections  : {len(auth_data)}  ({', '.join(s['name'] for s in auth_data) or 'none'})")
print(f"auth triggers (post-commit): {len(auth_triggers)}  "
      f"({', '.join(s['name'] for s in auth_triggers) or 'none'})")
print(f"wrote: {OUT}")
